import type { ImageItem } from "./types";

export const imageData: ImageItem[] = [
  {
    id: "1",
    imageUrl: "../assets/img5.webp",
    title: "Demo Title — 01",
    description: "Model: Demo Model 1",
    effect: "effect01",
  },
  {
    id: "2",
    imageUrl: "../assets/img17.webp",
    title: "Demo Title — 02",
    description: "Model: Demo Model 2",
    effect: "effect01",
  },
  {
    id: "3",
    imageUrl: "../assets/img8.webp",
    title: "Demo Title — 03",
    description: "Model: Demo Model 3",
    effect: "effect01",
  },
  {
    id: "4",
    imageUrl: "../assets/img2.webp",
    title: "Demo Title — 04",
    description: "Model: Demo Model 4",
    effect: "effect01",
  },
  {
    id: "5",
    imageUrl: "../assets/img13.webp",
    title: "Demo Title — 05",
    description: "Model: Demo Model 5",
    effect: "effect01",
  },
  {
    id: "6",
    imageUrl: "../assets/img25.webp",
    title: "Demo Title — 06",
    description: "Model: Demo Model 6",
    effect: "effect01",
  },
  {
    id: "7",
    imageUrl: "../assets/img19.webp",
    title: "Demo Title — 07",
    description: "Model: Demo Model 7",
    effect: "effect01",
  },
  {
    id: "8",
    imageUrl: "../assets/img6.webp",
    title: "Demo Title — 08",
    description: "Model: Demo Model 8",
    effect: "effect01",
  },
  {
    id: "9",
    imageUrl: "../assets/img27.webp",
    title: "Demo Title — 09",
    description: "Model: Demo Model 9",
    effect: "effect01",
  },
  {
    id: "10",
    imageUrl: "../assets/img11.webp",
    title: "Demo Title — 10",
    description: "Model: Demo Model 10",
    effect: "effect01",
  },
  {
    id: "11",
    imageUrl: "../assets/img3.webp",
    title: "Demo Title — 11",
    description: "Model: Demo Model 11",
    effect: "effect01",
  },
  {
    id: "12",
    imageUrl: "../assets/img30.webp",
    title: "Demo Title — 12",
    description: "Model: Demo Model 12",
    effect: "effect01",
  },
  {
    id: "13",
    imageUrl: "../assets/img9.webp",
    title: "Demo Title — 13",
    description: "Model: Demo Model 13",
    effect: "effect01",
  },
  {
    id: "14",
    imageUrl: "../assets/img1.webp",
    title: "Demo Title — 14",
    description: "Model: Demo Model 14",
    effect: "effect01",
  },
  {
    id: "15",
    imageUrl: "../assets/img33.webp",
    title: "Demo Title — 15",
    description: "Model: Demo Model 15",
    effect: "effect01",
  },
  {
    id: "16",
    imageUrl: "../assets/img10.webp",
    title: "Demo Title — 16",
    description: "Model: Demo Model 16",
    effect: "effect01",
  },

  {
    id: "17",
    imageUrl: "../assets/img15.webp",
    title: "Demo Title — 17",
    description: "Model: Demo Model 17",
    effect: "effect02",
  },
  {
    id: "18",
    imageUrl: "../assets/img7.webp",
    title: "Demo Title — 18",
    description: "Model: Demo Model 18",
    effect: "effect02",
  },
  {
    id: "19",
    imageUrl: "../assets/img4.webp",
    title: "Demo Title — 19",
    description: "Model: Demo Model 19",
    effect: "effect02",
  },
  {
    id: "20",
    imageUrl: "../assets/img21.webp",
    title: "Demo Title — 20",
    description: "Model: Demo Model 20",
    effect: "effect02",
  },
  {
    id: "21",
    imageUrl: "../assets/img12.webp",
    title: "Demo Title — 21",
    description: "Model: Demo Model 21",
    effect: "effect02",
  },
  {
    id: "22",
    imageUrl: "../assets/img29.webp",
    title: "Demo Title — 22",
    description: "Model: Demo Model 22",
    effect: "effect02",
  },
  {
    id: "23",
    imageUrl: "../assets/img20.webp",
    title: "Demo Title — 23",
    description: "Model: Demo Model 23",
    effect: "effect02",
  },
  {
    id: "24",
    imageUrl: "../assets/img14.webp",
    title: "Demo Title — 24",
    description: "Model: Demo Model 24",
    effect: "effect02",
  },
  {
    id: "25",
    imageUrl: "../assets/img22.webp",
    title: "Demo Title — 25",
    description: "Model: Demo Model 25",
    effect: "effect02",
  },
  {
    id: "26",
    imageUrl: "../assets/img26.webp",
    title: "Demo Title — 26",
    description: "Model: Demo Model 26",
    effect: "effect02",
  },
  {
    id: "27",
    imageUrl: "../assets/img16.webp",
    title: "Demo Title — 27",
    description: "Model: Demo Model 27",
    effect: "effect02",
  },
  {
    id: "28",
    imageUrl: "../assets/img23.webp",
    title: "Demo Title — 28",
    description: "Model: Demo Model 28",
    effect: "effect02",
  },
  {
    id: "29",
    imageUrl: "../assets/img28.webp",
    title: "Demo Title — 29",
    description: "Model: Demo Model 29",
    effect: "effect02",
  },
  {
    id: "30",
    imageUrl: "../assets/img31.webp",
    title: "Demo Title — 30",
    description: "Model: Demo Model 30",
    effect: "effect02",
  },
  {
    id: "31",
    imageUrl: "../assets/img24.webp",
    title: "Demo Title — 31",
    description: "Model: Demo Model 31",
    effect: "effect02",
  },
  {
    id: "32",
    imageUrl: "../assets/img32.webp",
    title: "Demo Title — 32",
    description: "Model: Demo Model 32",
    effect: "effect02",
  },

  {
    id: "33",
    imageUrl: "../assets/img18.webp",
    title: "Demo Title — 33",
    description: "Model: Demo Model 33",
    effect: "effect03",
  },
  {
    id: "34",
    imageUrl: "../assets/img3.webp",
    title: "Demo Title — 34",
    description: "Model: Demo Model 34",
    effect: "effect03",
  },
  {
    id: "35",
    imageUrl: "../assets/img6.webp",
    title: "Demo Title — 35",
    description: "Model: Demo Model 35",
    effect: "effect03",
  },
  {
    id: "36",
    imageUrl: "../assets/img9.webp",
    title: "Demo Title — 36",
    description: "Model: Demo Model 36",
    effect: "effect03",
  },
  {
    id: "37",
    imageUrl: "../assets/img33.webp",
    title: "Demo Title — 37",
    description: "Model: Demo Model 37",
    effect: "effect03",
  },
  {
    id: "38",
    imageUrl: "../assets/img2.webp",
    title: "Demo Title — 38",
    description: "Model: Demo Model 38",
    effect: "effect03",
  },
  {
    id: "39",
    imageUrl: "../assets/img1.webp",
    title: "Demo Title — 39",
    description: "Model: Demo Model 39",
    effect: "effect03",
  },
  {
    id: "40",
    imageUrl: "../assets/img8.webp",
    title: "Demo Title — 40",
    description: "Model: Demo Model 40",
    effect: "effect03",
  },
  {
    id: "41",
    imageUrl: "../assets/img5.webp",
    title: "Demo Title — 41",
    description: "Model: Demo Model 41",
    effect: "effect03",
  },
  {
    id: "42",
    imageUrl: "../assets/img17.webp",
    title: "Demo Title — 42",
    description: "Model: Demo Model 42",
    effect: "effect03",
  },
  {
    id: "43",
    imageUrl: "../assets/img11.webp",
    title: "Demo Title — 43",
    description: "Model: Demo Model 43",
    effect: "effect03",
  },
  {
    id: "44",
    imageUrl: "../assets/img4.webp",
    title: "Demo Title — 44",
    description: "Model: Demo Model 44",
    effect: "effect03",
  },
  {
    id: "45",
    imageUrl: "../assets/img10.webp",
    title: "Demo Title — 45",
    description: "Model: Demo Model 45",
    effect: "effect03",
  },
  {
    id: "46",
    imageUrl: "../assets/img30.webp",
    title: "Demo Title — 46",
    description: "Model: Demo Model 46",
    effect: "effect03",
  },
  {
    id: "47",
    imageUrl: "../assets/img13.webp",
    title: "Demo Title — 47",
    description: "Model: Demo Model 47",
    effect: "effect03",
  },
  {
    id: "48",
    imageUrl: "../assets/img7.webp",
    title: "Demo Title — 48",
    description: "Model: Demo Model 48",
    effect: "effect03",
  },

  {
    id: "49",
    imageUrl: "../assets/img16.webp",
    title: "Demo Title — 49",
    description: "Model: Demo Model 49",
    effect: "effect04",
  },
  {
    id: "50",
    imageUrl: "../assets/img12.webp",
    title: "Demo Title — 50",
    description: "Model: Demo Model 50",
    effect: "effect04",
  },
  {
    id: "51",
    imageUrl: "../assets/img14.webp",
    title: "Demo Title — 51",
    description: "Model: Demo Model 51",
    effect: "effect04",
  },
  {
    id: "52",
    imageUrl: "../assets/img18.webp",
    title: "Demo Title — 52",
    description: "Model: Demo Model 52",
    effect: "effect04",
  },
  {
    id: "53",
    imageUrl: "../assets/img19.webp",
    title: "Demo Title — 53",
    description: "Model: Demo Model 53",
    effect: "effect04",
  },
  {
    id: "54",
    imageUrl: "../assets/img20.webp",
    title: "Demo Title — 54",
    description: "Model: Demo Model 54",
    effect: "effect04",
  },
  {
    id: "55",
    imageUrl: "../assets/img21.webp",
    title: "Demo Title — 55",
    description: "Model: Demo Model 55",
    effect: "effect04",
  },
  {
    id: "56",
    imageUrl: "../assets/img22.webp",
    title: "Demo Title — 56",
    description: "Model: Demo Model 56",
    effect: "effect04",
  },
  {
    id: "57",
    imageUrl: "../assets/img23.webp",
    title: "Demo Title — 57",
    description: "Model: Demo Model 57",
    effect: "effect04",
  },
  {
    id: "58",
    imageUrl: "../assets/img24.webp",
    title: "Demo Title — 58",
    description: "Model: Demo Model 58",
    effect: "effect04",
  },
  {
    id: "59",
    imageUrl: "../assets/img25.webp",
    title: "Demo Title — 59",
    description: "Model: Demo Model 59",
    effect: "effect04",
  },
  {
    id: "60",
    imageUrl: "../assets/img26.webp",
    title: "Demo Title — 60",
    description: "Model: Demo Model 60",
    effect: "effect04",
  },
  {
    id: "61",
    imageUrl: "../assets/img27.webp",
    title: "Demo Title — 61",
    description: "Model: Demo Model 61",
    effect: "effect04",
  },
  {
    id: "62",
    imageUrl: "../assets/img28.webp",
    title: "Demo Title — 62",
    description: "Model: Demo Model 62",
    effect: "effect04",
  },
  {
    id: "63",
    imageUrl: "../assets/img29.webp",
    title: "Demo Title — 63",
    description: "Model: Demo Model 63",
    effect: "effect04",
  },
  {
    id: "64",
    imageUrl: "../assets/img31.webp",
    title: "Demo Title — 64",
    description: "Model: Demo Model 64",
    effect: "effect04",
  },
];
